### PR TITLE
Update genotypeClones parameters

### PR DESCRIPTION
**Pull request by andremrsantos**
update genotypeClones.py running parameters to reduce cell and BC dropped during processing

### CODE REVIEW

**Comment by andremrsantos** [comment]
FYI the following lines make that `--transfectionKey` required to be "transfection" to remain consistent with other steps. Should we fix this issue?

https://github.com/mauranolab/mapping/blob/0e60b75db27a25d0d047427ca522f392591c5a9f/transposon/genotypeClones.py#L576
https://github.com/mauranolab/mapping/blob/0e60b75db27a25d0d047427ca522f392591c5a9f/transposon/genotypeClones.py#L579

**Comment by mattmaurano** [comment]
Looks like this is your code -- what is going on here? What are you suggesting to fix?
> https://github.com/mauranolab/mapping/blob/0e60b75db27a25d0d047427ca522f392591c5a9f/transposon/genotypeClones.py#L577-L579

**Comment by mattmaurano** [comment]
Also, how was --maxpropreads working as an int with a default of 0.1?

**Comment by andremrsantos** [comment]
- Yes, the code is mine. But it should be using `args.transfectionKey` as key for the transfection value (see example below) or we can forget this argument and just default to `"transfection"` as key

```
assignToNodes(G, args.transfectionKey, bcToTransfection, default="None")
(...)
for n in G.nodes:
    if G.nodes[n]['type'] == 'cell':
        G.nodes[n][args.transfectionKey] = 'cellBC' 
```

- regarding `--maxpropreads`, I was surprise too but it seem to work before, it only failed when I try to assign different value. I guess `argparser` don't check the default value since the namespace print in our log appear as `maxpropreads=0.10`.

**Comment by mattmaurano** [comment]
I see, yes switch to args.transfectionKey

Also add a comment about what that for loop is doing, you set the transfection to cellBC for each cell node -- why again?

**Comment by andremrsantos** [comment]
I was running a test-drive and the code wasn't running because I hadn't defined NSLOTS, maybe we should note somewhere it must be defined to execute `submitMerge.sh`

**Comment by mattmaurano** [comment]
NSLOTS is defined by qsub, but see also my .bashrc

That';s why there's this in submitMerge:
#export NSLOTS=1

--Matt

**Comment by andremrsantos** [comment]
Also, since we are renaming stuff can we replace `blacklist` and `whitelist` for `killList` and `keepList`, respectively, or something like this?

**Comment by mattmaurano** [comment]
black/white is standard, what's the issue?

--Matt

**Comment by andremrsantos** [comment]
They are standard, but due to the racial connotation there has been some movement to replace them. I just thought would be better to avoid unnecessary critics.
I've look into the code and we only use them in two files, both of them we are updating here.

**Comment by andremrsantos** [comment]
My test-drive ran worked fine soo far. See log at: http://cascade.isg.med.nyu.edu/~ribeia01/scratch/transposon_10x/TestGenotypeCLones/BSmany-20200804_T0219A_T0220B_T0221B_T0222B_10xRNA.o4815570

**Pull request merged**
