### PR TITLE
Permit passing separate bam file to count reads for normalization

### LINKED ISSUE #228: Permit passing separate bam file to count reads for normalization
John,

Can you add a new --normbam argument to submit_bamintersect.sh? If provided, it should be used for the normalization calculation (currently num_bam1_reads). It should default to bam1.

### PR DESCRIPTION
**Pull request by cadley-nyulangone**
The optional normbam parameter is passed to merge_bamintersect.sh, and is used there instead of bam1 as the basis for counting reads for normalization.

Also fixed a typo in HA_table.sh   --readNames ==> --include_readnames
This change was overlooked in the "stop making .counts.informative.bed files as their utility is reduced" commit.

fixes #228

### CODE REVIEW

**Review by cadley-nyulangone — COMMENTED** [review]
Taking the brackets from around the 10 in normbam=${10} will break the code.  normbam will end up with contents like this:  "${1}0"

**Review by cadley-nyulangone — COMMENTED** [review]
Now this will be a problem:  verbose=$10

**Comment by cadley-nyulangone** [comment]
Matt,

 verbose=$10  won't crash the code, but it prevents verbose from ever being
True.

verbose=$10   ==>  verbose=${1}0   ==>  verbose=${sampleOutdir}0

So verbose != True, even if the 10th parameter is set that way,   This
doesn't otherwise affect the code, but it disables the functionality of the
verbose parameter.

John

**Comment by mattmaurano** [comment]
John, you're saying bash parses $10 as $1 followed by a 0?

**Comment by mattmaurano** [comment]
Uggh. Then go ahead and make a PR to use curly braces for all the $1, etc. variables in the whole dnase pipeline.

**Comment by cadley-nyulangone** [comment]
Yes, that's exactly what it does.

**Comment by cadley-nyulangone** [comment]
OK

**Pull request merged**
