### PR TITLE
speed-up filterNodesFromFile

### PR DESCRIPTION
**Pull request by andremrsantos**
This is a quick speed-up when filtering nodes based on whitelist or blacklist

### CODE REVIEW

**Comment by mattmaurano** [comment]
How does this work? Doesn't Graph.remove_edge() require an edge, not a node?

**Comment by andremrsantos** [comment]
> How does this work? Doesn't Graph.remove_edge() require an edge, not a node?

I replaced the iterative check of all edges with `G.edges(nodesToRemove)` that return a "list" of edges incident to the nodes within `nodesToRemove` (see [documentation](https://networkx.org/documentation/stable/reference/classes/generated/networkx.Graph.edges.html)).

I've made that substitution because the current algorithm (see original below) has a complexity of `O(EN)`  since it checks all edges (`E`) if either nodes are contained in `nodesToRemove` that is a list and takes `O(N)` to check inclusion. Alternatively, we can convert `nodesToRemove` to a `set` which would make inclusion `O(1)`, but I think the library function is probably faster.

```
[edge for edge in G.edges if edge[0] in nodesToRemove or edge[1] in nodesToRemove]
```

**Comment by mattmaurano** [comment]
right, that makes sense. But when I look at the docs https://networkx.org/documentation/stable//reference/classes/generated/networkx.Graph.remove_edge.html , remove_edge should be passed edges, not nodes, right?

**Comment by andremrsantos** [comment]
Yes, for either `G.remove_edge` or `G.remove_edges_from` you need to pass edges, but I am not using either of them here. I am using the library `remove_edges` instead.

**Comment by mattmaurano** [comment]
Oh, that's not a networkx function, that is defined below. But it still assumes it is getting an edge. Does [e for e in G.edges if e in edgesToRemove] turn the list of nodes into a list of edges?

**Comment by andremrsantos** [comment]
No, I am passing a list of edges to `remove_edges()` that I generated using the function `G.edges(nodesToRemove)`.

**Comment by mattmaurano** [comment]
Oh, I see now -- the way github colored the diff got me really confused.

**Pull request merged**
