### PR TITLE
Normalize reads reported in counts.txt files to reads per 10mm

### PR DESCRIPTION
**Pull request by cadley-nyulangone**
<pre>
new reads reported = int(10,000,000 * (number of reads in the range) / (total reads from the sample) + 0.5)
                                       ============================
                                      This is what we currently report
</pre>

total reads is computed this way:
<pre>
    num_bam1_reads=$(samtools view -c -F 512 ${bam1})
</pre>

### CODE REVIEW

**Comment by cadley-nyulangone** [comment]
fixes #217

**Review by mattmaurano — COMMENTED** [review]
Am I reading this wrong, or is num_bam1_reads never set?

**Comment by cadley-nyulangone** [comment]
It's set in line 65 of merge_bamintersect.sh

It's passed into counts_table.sh in line 33 there.

**Comment by mattmaurano** [comment]
great

you need to update help message in submit_bamintersect.sh

**Comment by mattmaurano** [comment]
I fixed this

**Pull request merged**
