### PR TITLE
add postCleanUp method interface to genotypeClones

### PR DESCRIPTION
**Pull request by andremrsantos**
Added `postCleanUp` method to `genotypeClones.py` to remove conflict cells and breakup conflict clones

### CODE REVIEW

**Comment by mattmaurano** [comment]
Looks like it's hardcoded to look for a key "transfection". How about taking the key name as a command line parameter?

**Comment by andremrsantos** [comment]
Sure thing, I've pushed a new commit adding the `transfectionAnnotation` parameter and avoid hard-coding.

**Comment by mattmaurano** [comment]
I mean change postCleanUp from a flag to a parameter

Then you can pass in "transfection" from analyzeBC.sh

**Comment by andremrsantos** [comment]
Yes, I've added `--transfectionAnnotation` parameter that is defined from CLI and default it to `transfection`.

**Comment by mattmaurano** [comment]
Best not hardcode a default in the python code. Rather, pass it in from analyzeBCcounts.sh

**Comment by andremrsantos** [comment]
I've removed the default value and added some checks of the `transfectionAnnotation` values during execution.

**Comment by mattmaurano** [comment]
Is there a need for both --postCleanUp and --transfectionAnnotation? How about a single option --splitConflictingClones [keyName]?

You will need to update analyzeBCcounts.sh to add --splitConflictingClones transfection to the genotypeClones.pl call

**Comment by andremrsantos** [comment]
Sure, I've consolidated these options into `splitConflictingClones` parameter and added it to `analyzeBCcounts.sh`

**Comment by andremrsantos** [comment]
BTW, it

**Comment by andremrsantos** [comment]
Sorry, I pressed the wrong button.

**Comment by mattmaurano** [comment]
excellent, this is a flexible interface that could be used for other purposes

**Pull request merged**
